---
title: "Database manipulation"
output:
  html_document:
    highlight: tango
    df_print: paged
---

---

## Start with a question!

### _How did the Average Statuatory Reserve change from 1Q16 to 3Q16?_

#### Specifically, we want to look at the change in stat reserve for each _Plancode_ and for each _Sex_. 

---

```{r, message = FALSE, include = FALSE}
library(DBI)
library(dbplyr)
library(tidyverse)
```

### Connect to the database, and the tables required

```{r, warning=FALSE}
# Connect to database
cn <- dbConnect(drv = odbc::odbc(), dsn = "fictrad")

# Connect to the 1q16 table
tbl_1q16 <- tbl(cn, "1q16")

# Connect to the 3q16 table
tbl_3q16 <- tbl(cn, "3q16")

# What does this look like?
tbl_1q16
```

### Pull those tables into R and join them together

```{r}
start_time <- proc.time()

# Add a new column, then select the 4 columns that interest us
tbl_1q16 <- tbl_1q16 %>%
  mutate(quarter = "1q16") %>%                             
  select(`//ALFA_PLANCODE`, ALFA_Sex, quarter, InitStatRes) 
  
# Add a new column, then select the 4 columns that interest us
tbl_3q16 <- tbl_3q16 %>%
  mutate(quarter = "3q16") %>%                              
  select(`//ALFA_PLANCODE`, ALFA_Sex, quarter, InitStatRes)

# Combine the two datasets
joined_data <- bind_rows(collect(tbl_1q16),
                         collect(tbl_3q16))

proc.time() - start_time
```

### But how much data was this?

```{r}
dim(joined_data)

joined_data
```

### Average Statuatory Reserve from 1q16 -> 3q16

#### Broken down by Plancode and Sex 

```{r}
joined_data %>%
  
  # Grouping by plancode, sex, and quarter
  group_by(`//ALFA_PLANCODE`, ALFA_Sex, quarter) %>%
  
  # For each group, calculate the average stat reserve
  summarise(avg_stat_reserve = mean(InitStatRes)) %>%
  
  # Spread it out by quarter so you can compare the two
  spread(key = quarter, value = avg_stat_reserve)
```


